<a href="https://colab.research.google.com/github/isnanramalia/klasifikasi-siswa-dropout/blob/main/decisiontreeuts_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# library

In [ ]:
# import library
import numpy as np
import pandas as pd
from sklearn import tree

In [ ]:
data = pd.read_csv('data_smk_askha_1.csv')

In [ ]:
data.head()

,JK,Tanggal Lahir,Tempat Lahir,Asal Kecamatan,Jenis Tinggal,Alat Transportasi,Jenjang Pendidikan Ayh,Pekerjaan Ayh,Penghasilan Ayh,Jenjang Pendidikan Ibu,Pekerjaan Ibu,Penghasilan Ibu,Keluar Karena
0,L,2003-01-28,SEMARANG,Cilacap Tengah,Bersama orang tua,Sepeda,SMP / sederajat,Wiraswasta,"Rp. 5,000,000 - Rp. 20,000,000",D3,Karyawan Swasta,"Rp. 2,000,000 - Rp. 4,999,999",Lulus
1,L,2004-11-14,SEMARANG,Mijen,Bersama orang tua,Jalan kaki,SMA / sederajat,Karyawan Swasta,"Rp. 500,000 - Rp. 999,999",SMP / sederajat,Karyawan Swasta,"Rp. 2,000,000 - Rp. 4,999,999",Lulus
2,L,2006-05-26,Semarang,Ngaliyan,Bersama orang tua,Ojek,SD / sederajat,Karyawan Swasta,"Rp. 1,000,000 - Rp. 1,999,999",SMP / sederajat,Tidak bekerja,Tidak Berpenghasilan,Mutasi
3,L,1998-07-08,TEGAL,Balapulang,Panti asuhan,Sepeda motor,SD / sederajat,Buruh,"Rp. 1,000,000 - Rp. 1,999,999",SD / sederajat,Buruh,"Rp. 1,000,000 - Rp. 1,999,999",Lulus
4,L,1995-12-18,SEMARANG,Semarang,Asrama,Jalan kaki,SD / sederajat,Petani,NaN,SD / sederajat,Petani,NaN,Lulus

# Preprocessing Data

In [ ]:
data['Tanggal Lahir'] = pd.to_datetime(data['Tanggal Lahir']).dt.year

In [ ]:
data.head()

,JK,Tanggal Lahir,Tempat Lahir,Asal Kecamatan,Jenis Tinggal,Alat Transportasi,Jenjang Pendidikan Ayh,Pekerjaan Ayh,Penghasilan Ayh,Jenjang Pendidikan Ibu,Pekerjaan Ibu,Penghasilan Ibu,Keluar Karena
0,L,2003,SEMARANG,Cilacap Tengah,Bersama orang tua,Sepeda,SMP / sederajat,Wiraswasta,"Rp. 5,000,000 - Rp. 20,000,000",D3,Karyawan Swasta,"Rp. 2,000,000 - Rp. 4,999,999",Lulus
1,L,2004,SEMARANG,Mijen,Bersama orang tua,Jalan kaki,SMA / sederajat,Karyawan Swasta,"Rp. 500,000 - Rp. 999,999",SMP / sederajat,Karyawan Swasta,"Rp. 2,000,000 - Rp. 4,999,999",Lulus
2,L,2006,Semarang,Ngaliyan,Bersama orang tua,Ojek,SD / sederajat,Karyawan Swasta,"Rp. 1,000,000 - Rp. 1,999,999",SMP / sederajat,Tidak bekerja,Tidak Berpenghasilan,Mutasi
3,L,1998,TEGAL,Balapulang,Panti asuhan,Sepeda motor,SD / sederajat,Buruh,"Rp. 1,000,000 - Rp. 1,999,999",SD / sederajat,Buruh,"Rp. 1,000,000 - Rp. 1,999,999",Lulus
4,L,1995,SEMARANG,Semarang,Asrama,Jalan kaki,SD / sederajat,Petani,NaN,SD / sederajat,Petani,NaN,Lulus

In [ ]:
data["JK"] = pd.factorize(data.JK)[0]
data["Tempat Lahir"] = pd.factorize(data["Tempat Lahir"])[0]
data["Asal Kecamatan"] = pd.factorize(data["Asal Kecamatan"])[0]
data["Jenis Tinggal"] = pd.factorize(data["Jenis Tinggal"])[0]
data["Alat Transportasi"] = pd.factorize(data["Alat Transportasi"])[0]
data["Jenjang Pendidikan Ayh"] = pd.factorize(data["Jenjang Pendidikan Ayh"])[0]
data["Pekerjaan Ayh"] = pd.factorize(data["Pekerjaan Ayh"])[0]
data["Penghasilan Ayh"] = pd.factorize(data["Penghasilan Ayh"])[0]
data["Jenjang Pendidikan Ibu"] = pd.factorize(data["Jenjang Pendidikan Ibu"])[0]
data["Pekerjaan Ibu"] = pd.factorize(data["Pekerjaan Ibu"])[0]
data["Penghasilan Ibu"] = pd.factorize(data["Penghasilan Ibu"])[0]
data["Keluar Karena"] = pd.factorize(data["Keluar Karena"])[0]

In [ ]:
data = data.to_numpy()

In [ ]:
print(data)

[[   0 2003    0 ...    0    0    0]
 [   0 2004    0 ...    0    0    0]
 [   0 2006    1 ...    1    1    1]
 ...
 [   1 1997    4 ...    3   -1    0]
 [   1 2001    0 ...    0    2    0]
 [   1 2003    1 ...    0    0    0]]

# Proses Data

In [ ]:
dataTraining = np.concatenate((data[0:400, :], data[500:900, :]), axis=0)
dataTesting = np.concatenate((data[400:500, :], data[900:1000, :]), axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[   0 2003    0 ...    0    0    0]
 [   0 2004    0 ...    0    0    0]
 [   0 2006    1 ...    1    1    1]
 ...
 [   1 2004    4 ...    6    3    0]
 [   1 2003    0 ...    2    3    0]
 [   1 2000    0 ...    1   -1    0]]

800

In [ ]:
print(dataTesting)
len(dataTesting)

[[   0 2000    4 ...    5    3    0]
 [   0 1998    0 ...    1   -1    0]
 [   0 1999    4 ...    3   -1    0]
 ...
 [   0 1998    0 ...    5   -1    0]
 [   0 2003    0 ...    1    1    0]
 [   0 1997    4 ...    1   -1    1]]

200

In [ ]:
inputTraining = dataTraining[:, 0:11]
inputTesting = dataTesting[:, 0:11]
labelTraining = dataTraining[:, 11]
labelTesting = dataTesting[:, 11]
print(labelTraining)
len(labelTraining)

[ 0  0  1  2 -1 -1  2 -1 -1 -1 -1  3  3  2 -1  2  2 -1 -1  2 -1  2  2  2
 -1  2 -1  2  2  4  0  3  0  3  3  3  3  3 -1 -1 -1  1  4  2  0  3  2 -1
  2  3 -1 -1  2  3  2 -1  1 -1  2 -1  3 -1  3  2  3  1 -1 -1 -1  3 -1 -1
 -1  2  3 -1 -1  3  3  0  3  1  4  1  2  1 -1  3  1 -1  2  1  4  2  3  0
  3 -1  2 -1  2  2 -1  1  4  0  3  2 -1 -1  3  2  3 -1  1  3  3  2  3  3
  3  3  3  1  1 -1 -1  1  2  1  2  2  2  3  3  3  2  2 -1  1 -1  4  2  2
 -1  4 -1  1  3  2 -1 -1  2 -1  2  0  0  2 -1  2 -1  3  3 -1  5  4  2  0
  4 -1  2 -1 -1  3  3  1 -1 -1  2  3  3 -1  4  3 -1  1 -1  4  3  4  3  3
  2  3  1  3  3  3  1  1 -1  2  2  4  1  1  2  3 -1  2 -1  0  3  2  3 -1
  3  2  1 -1  1  2  2  2  3  3 -1 -1 -1  4  2  3  0  3  2 -1 -1 -1  3  0
  4  3  0  2  2  2 -1  2  2  1 -1  3  2  2 -1  4  0 -1 -1 -1  2  2 -1 -1
  2  3  2  0  3  3 -1  0  1  1  1  1 -1  3  1 -1  1  2  2  2  4  1  3  2
  0  2 -1  1  3  2  2  2  0 -1  2  3  2  2  2  3  2 -1  2  2  1  2  2  3
  2  1 -1 -1  2 -1 -1  2 -1 -1  3  3  3  3  1  2 -1  3 -1  4  2  2  2  1
 -1  3  1  3  4  3 -1  1  1  3  2  3  2  1  3 -1  3  2  1 -1  2  2  3  0
 -1 -1  3  3  2 -1  3 -1  2  2 -1  3 -1  1 -1 -1 -1  3  2  2  2  1  4  2
 -1 -1 -1  1  3  3 -1  3  2  4 -1  3 -1  2 -1 -1  1 -1 -1 -1  1 -1  3 -1
 -1  3 -1  2 -1  1  2  3 -1  2  2  2  1 -1  4  3  4 -1  4  0  2  2  3  4
  4  0 -1  2  4  2  1  1 -1  3  2  1  2  3 -1 -1 -1  3  3 -1 -1  1 -1  2
 -1  4 -1  0 -1  4  3 -1 -1  2  4 -1  0  3 -1  3 -1  1 -1  4  3  1  3  1
 -1 -1 -1 -1  1 -1  0  0 -1 -1  3  3  2  2 -1  3 -1  3  3  4  2 -1  2  1
  4  4 -1  3 -1  3  2  1  2  3  2  1 -1  3  2  2  1  1  2  2  2  1  3  2
 -1  2  3  2 -1  2  0  3  3 -1 -1 -1 -1 -1 -1  1  2 -1  3  3 -1  2 -1  2
 -1  2  3  1  2  1  0  3 -1  2  1  3  2  2  3  0 -1  2  3  2  3  2  3 -1
 -1  3 -1  1 -1  1  1 -1  1  4  1 -1  1 -1 -1 -1  3  2  2  2 -1  2  2  2
 -1  1 -1 -1 -1 -1 -1  1  3  1  2  3  4  2  1  2  2 -1  2  2  2  3  3 -1
  2  2  3 -1  2  2 -1  4  3 -1  1  0 -1  2 -1  2  1  2  2 -1 -1 -1  1  3
  1  3 -1 -1  3 -1  1 -1 -1  0  2  3 -1 -1 -1  3 -1 -1  2  0 -1 -1  2 -1
  1  1  1  2 -1 -1  1  1  2  2  1  3  2  0  1 -1  1  2 -1  0  1 -1  3 -1
  2  3  3  0  2  0  0  3  4  2  1  2  4 -1  1  4  3 -1  1 -1  4 -1  1  2
  1  0 -1  3  3  2  3  2  1 -1  3  2  0 -1 -1  1  3  0  1 -1  1  2  1 -1
  3 -1  2  2  0  3  2  2 -1 -1  2  2 -1 -1 -1  2  1  3  3  3  1  2  4  1
  2  3 -1  2  2  2  2  1 -1  3  1  2  2  2  2 -1 -1  2  2 -1  3  0 -1 -1
 -1  2  2 -1  1  3  3 -1]

800

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
model = model.fit(inputTraining, labelTraining)

In [ ]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya: ", labelTesting)
print("Hasil Prediksi: ", hasilPrediksi)

Label Sebenarnya:  [ 3 -1 -1  2 -1 -1 -1  1 -1  4  2 -1 -1  2 -1  0  2  2  1  4  1 -1 -1  2
 -1  3 -1  3  2 -1  2 -1  2 -1 -1  0  3  2  3 -1 -1  4  3 -1 -1  2  2  2
 -1  2  0  2 -1  3 -1  2 -1 -1  3 -1  2 -1  1  1  4 -1  0  2  2  2  2  2
  3  3  3  2 -1 -1  2  2 -1  3  3  4  3 -1  1  1  2  2  2  1  3  4  2 -1
  3 -1  4 -1  4 -1 -1 -1 -1  3 -1  1  2 -1 -1  3  2 -1 -1 -1 -1  1 -1 -1
  1 -1  2 -1 -1  3 -1  0  0  2  2  1 -1  2  1  2  2  2 -1  2 -1 -1  2  2
  2  1 -1  3  2  2  4  1  1  2 -1  0  3  3  3  1  4  2 -1  2  1  2 -1 -1
  3 -1 -1  2  2 -1  1  3  3  2 -1 -1 -1  3  1  2 -1  1  4  3 -1  2  2  2
 -1  2 -1  4  2 -1  1 -1]
Hasil Prediksi:  [ 2 -1 -1  2 -1 -1 -1  1 -1  2  2 -1 -1  3  2  2  0  3  1  4  4 -1 -1  2
 -1  3 -1  3  3 -1  2  2  2 -1 -1  2  3  4  2 -1 -1  4  2  3 -1  2  2  3
 -1  3  2  2 -1  2 -1  0 -1 -1 -1  1  2 -1  1  3  4  1  2  3  2  2  2  0
  3  3  1  0 -1 -1  3  2 -1  2  2  4  3 -1  4  1  2  3  2 -1  2  1  0 -1
  2 -1  2 -1  2  0 -1 -1 -1  3 -1  1  2 -1 -1  1  2 -1 -1 -1 -1  1  3  3
 -1 -1  0 -1 -1  2 -1  0  0  0 -1  3 -1  2 -1  3  3  2 -1  2 -1 -1  2  0
  2 -1 -1  3  0  2  3  1  1  2 -1  3  2  2  2  1  4  2 -1  2  1  2 -1 -1
  3 -1 -1  3  3 -1  1  2  2  3 -1 -1 -1  3  1  3 -1  1  2  2 -1  3  2  2
 -1  2  0  4  3 -1  1 -1]

In [ ]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar: ", prediksiBenar, "data")
print("Prediksi Salah: ", prediksiSalah, "data")
print("Akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)* 100, "%")

Prediksi Benar:  127 data
Prediksi Salah:  73 data
Akurasi:  63.5 %